volumes:
  data:
  rabbitmq-data:

networks:
  my-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ronny
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    networks:
      - my-network
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      # - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      # - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network
    restart: always

  realmx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./r3almX_backend:/app/r3almX_backend
    depends_on:
      - postgres
      - redis
      - rabbitmq

    networks:
      - my-network
