name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install toml semantic-version

      - name: Bump Version
        run: |
          python -c "import toml, semantic_version; \
                     with open('pyproject.toml', 'r') as f: data = toml.load(f); \
                     current_version = semantic_version.Version(data['tool']['semantic-version']['current_version']); \
                     new_version = current_version.next_patch(); \
                     data['tool']['semantic-version']['current_version'] = str(new_version); \
                     with open('pyproject.toml', 'w') as f: toml.dump(data, f); \
                     print('Version bumped to:', new_version);"

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add pyproject.toml
          git commit -m "Bump version to $(python -c 'import toml; print(toml.load(open("pyproject.toml"))["tool"]["semantic-version"]["current_version"])')"
          git push
